# Generated by Django 3.2.15 on 2022-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MylinebotApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
