# Generated by Django 4.1.1 on 2022-10-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MylinebotApp', '0003_user_info_asml_user_info_ctbc_user_info_cathay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='Chunghwa',
            new_name='Hsinchu',
        ),
    ]
